name: windows_deploy_mingw-w64

on:
  push:
  pull_request:
    types: [workflow_dispatch]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { sys: ucrt64, env: ucrt-x86_64 }
    
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - id: download
      uses: robinraju/release-downloader@v1
      with:
        repository: 'JonathSpirit/FastEngine'
        fileName: 'FastEngine-windows-ucrt-x86_64-ucrt64.zip'
        latest: true
        preRelease: true
        extract: true
    
    - name: test
      run: echo ${{ steps.download.outputs.downloaded_files }}
    
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        update: true
        install: curl git mingw-w64-${{matrix.env}}-gcc mingw-w64-${{matrix.env}}-make
    
    - name: Downloading cmake
      run: |
        curl -O "https://repo.msys2.org/mingw/${{matrix.sys}}/mingw-w64-${{matrix.env}}-cmake-3.30.5-1-any.pkg.tar.zst"
    
    - name: Installing cmake
      run: |
        pacman -U --noconfirm "mingw-w64-${{matrix.env}}-cmake-3.30.5-1-any.pkg.tar.zst"
    
    - name: Create Build Environment
      run: cmake -E make_directory "${{github.workspace}}\build"
    
    - name: Get number of CPU cores
      uses: SimenB/github-actions-cpu-cores@v2
      id: cpu-cores
    
    - name: Configure CMake
      working-directory: ${{github.workspace}}\build
      run: cmake $GITHUB_WORKSPACE -G "MinGW Makefiles" -D CMAKE_BUILD_TYPE=$BUILD_TYPE -D CMAKE_MODULE_PATH="$GITHUB_WORKSPACE/${{ fromJson(steps.download.outputs.downloaded_files)[0] }}"
    
    - name: Build
      working-directory: ${{github.workspace}}\build
      run: cmake --build . -j ${{steps.cpu-cores.outputs.count}} --config $BUILD_TYPE
    
    - name: Installing
      working-directory: ${{github.workspace}}\build
      run: cmake --install .
    
    #- uses: actions/upload-artifact@v4
    #  with:
    #    name: FastEngine-windows-${{matrix.env}}-${{matrix.sys}}
    #    path: ${{github.workspace}}\install\FastEngine*
    #    if-no-files-found: error
    #    retention-days: 3
    #    compression-level: 9
